---
- hosts: all
  become: true

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - vagrant
    - role: andrewrothstein.kubectl
    - role: andrewrothstein.minikube

  tasks:
    - name: update cache
      apt: update_cache=yes cache_valid_time=86400 #One day

    - name: install additional tools
      apt:
        state: present
        name:
          - net-tools
          - curl
          - htop

    - name: start minikube
      command: sudo -u vagrant bash -c "minikube start --driver=docker"